import type { PromptFormat } from '@/lib/types';

/**
 * Returns detailed structural rules and formatting guidelines for each
 * supported prompt format. These instructions are embedded in the meta-prompt
 * so Claude knows exactly how to structure its output.
 */
export function getFormatInstructions(format: PromptFormat): string {
  switch (format) {
    case 'xml':
      return [
        'Output Format: XML (Anthropic Official)',
        '',
        'Structure the prompt using Anthropic\'s recommended XML tag format:',
        '',
        '<system_prompt>',
        '  <role>The role or persona Claude should adopt</role>',
        '  <task>Clear description of the primary task</task>',
        '  <rules>',
        '    <rule>Specific behavioral constraint or guideline</rule>',
        '  </rules>',
        '  <format>Expected output structure and formatting</format>',
        '  <examples>',
        '    <example>',
        '      <input>Example user input</input>',
        '      <output>Expected model output</output>',
        '    </example>',
        '  </examples>',
        '  <context>Any background information or domain knowledge</context>',
        '</system_prompt>',
        '',
        'Rules:',
        '- Use self-closing or paired XML tags consistently',
        '- Nest related content inside parent tags',
        '- Keep tag names lowercase and hyphenated (e.g., <output-format>)',
        '- Include at least one <example> when the task benefits from demonstration',
        '- Use <thinking> tags if the prompt benefits from chain-of-thought reasoning',
      ].join('\n');

    case 'toon':
      return [
        'Output Format: TOON (Block Header Format)',
        '',
        'Structure the prompt using bracketed block headers:',
        '',
        '[ROLE]',
        'Define the persona or expertise Claude should adopt.',
        '',
        '[TASK]',
        'Describe the primary objective clearly and completely.',
        '',
        '[RULES]',
        '- Rule 1: Specific constraint',
        '- Rule 2: Another guideline',
        '',
        '[OUTPUT]',
        'Describe the expected output format and structure.',
        '',
        '[EXAMPLES]',
        'Input: Example input',
        'Output: Expected output',
        '',
        'Rules:',
        '- Use ALL-CAPS block headers in square brackets',
        '- Each block should be separated by a blank line',
        '- Use bullet points or numbered lists within blocks',
        '- [ROLE] and [TASK] are required; [RULES], [OUTPUT], [EXAMPLES] are recommended',
        '- Keep block content focused and avoid mixing concerns across blocks',
      ].join('\n');

    case 'harness':
      return [
        'Output Format: Harness Style (YAML-like Structured)',
        '',
        'Structure the prompt using YAML-like key-value metadata:',
        '',
        'name: "Short descriptive name for this prompt"',
        'description: "One-line summary of what this prompt does"',
        'system: |',
        '  Multi-line system prompt content.',
        '  Defines role, constraints, and behavior.',
        'user: |',
        '  Template for the user message.',
        '  Use {{variable}} for dynamic placeholders.',
        'constraints:',
        '  - Constraint or rule 1',
        '  - Constraint or rule 2',
        'output_format: "Description of expected output"',
        'examples:',
        '  - input: "Example input"',
        '    output: "Expected output"',
        '',
        'Rules:',
        '- Use YAML syntax with proper indentation (2 spaces)',
        '- Multi-line strings use the | (literal block scalar) indicator',
        '- Use {{placeholder}} syntax for dynamic variables',
        '- Include name and description as top-level metadata',
        '- Separate system prompt from user template clearly',
      ].join('\n');

    case 'markdown':
      return [
        'Output Format: Markdown',
        '',
        'Structure the prompt using standard Markdown:',
        '',
        '# Prompt Title',
        '',
        '## Role',
        'Describe the persona or expertise.',
        '',
        '## Task',
        'Clear description of the objective.',
        '',
        '## Rules',
        '- Rule 1',
        '- Rule 2',
        '',
        '## Output Format',
        'Describe the expected output structure.',
        '',
        '## Examples',
        '### Example 1',
        '**Input:** Example input',
        '**Output:** Expected output',
        '',
        'Rules:',
        '- Use # for title, ## for sections, ### for subsections',
        '- Use bullet lists (- or *) for rules and constraints',
        '- Use **bold** for emphasis on key terms',
        '- Use `code blocks` for technical content or exact formatting',
        '- Keep it readable and scannable for human review',
      ].join('\n');

    case 'plaintext':
      return [
        'Output Format: Plain Text',
        '',
        'Write the prompt as natural language paragraphs with no special formatting:',
        '',
        'Start with the role or persona statement.',
        '',
        'Then describe the task in clear, direct sentences.',
        '',
        'List any rules or constraints in natural prose.',
        '',
        'Describe the expected output.',
        '',
        'Provide examples if helpful.',
        '',
        'Rules:',
        '- No Markdown, XML, or other markup',
        '- Use paragraph breaks to separate logical sections',
        '- Write in clear, direct, professional prose',
        '- Keep sentences concise and unambiguous',
        '- The prompt should read like well-written instructions to a colleague',
      ].join('\n');

    case 'json':
      return [
        'Output Format: JSON',
        '',
        'Structure the prompt as a JSON object:',
        '',
        '{',
        '  "role": "The role or persona description",',
        '  "task": "Primary task description",',
        '  "rules": [',
        '    "Rule 1",',
        '    "Rule 2"',
        '  ],',
        '  "format": "Expected output format description",',
        '  "examples": [',
        '    {',
        '      "input": "Example input",',
        '      "output": "Expected output"',
        '    }',
        '  ],',
        '  "context": "Background information or domain knowledge"',
        '}',
        '',
        'Rules:',
        '- Output must be valid JSON (parseable by JSON.parse)',
        '- Use double quotes for all strings',
        '- Arrays for lists of rules and examples',
        '- Escape special characters properly within strings',
        '- Include all relevant keys even if some values are empty strings',
      ].join('\n');

    case 'yaml':
      return [
        'Output Format: YAML Config',
        '',
        'Structure the prompt as YAML key-value pairs:',
        '',
        'role: >',
        '  The role or persona description.',
        'task: >',
        '  Primary task description.',
        'rules:',
        '  - Rule 1',
        '  - Rule 2',
        'format: >',
        '  Expected output format description.',
        'examples:',
        '  - input: "Example input"',
        '    output: "Expected output"',
        'context: >',
        '  Background information or domain knowledge.',
        '',
        'Rules:',
        '- Use standard YAML syntax',
        '- Multi-line strings use > (folded) or | (literal) scalar indicators',
        '- Use 2-space indentation consistently',
        '- Lists use the - prefix',
        '- Keep key names lowercase and concise',
      ].join('\n');

    case 'claudemd':
      return [
        'Output Format: Claude.md (Claude Code Project Rules)',
        '',
        'Structure the prompt as a Claude Code CLAUDE.md project file:',
        '',
        '# Role',
        '',
        'Define the persona, expertise, and behavioral identity.',
        '',
        '## Task',
        '',
        'Describe the primary objective and scope.',
        '',
        '## Rules',
        '',
        '- Rule 1: Specific behavioral constraint',
        '- Rule 2: Another guideline',
        '',
        '## Output Format',
        '',
        'Describe the expected response structure.',
        '',
        '## Examples',
        '',
        '```',
        'Input: Example input',
        'Output: Expected output',
        '```',
        '',
        '## Background',
        '',
        'Domain knowledge, tech stack, or project context.',
        '',
        'Rules:',
        '- Use # for the top-level Role heading',
        '- Use ## for major sections (Task, Rules, Output Format, Examples, Background)',
        '- Use bullet lists for rules and constraints',
        '- Use fenced code blocks (```) for examples and code',
        '- This format is designed to be saved as CLAUDE.md in a project root',
        '- Keep it authoritative and directive in tone',
      ].join('\n');

    case 'system-user-split':
      return [
        'Output Format: System + User Split',
        '',
        'Structure the prompt as separate system and user messages in JSON:',
        '',
        '{',
        '  "system": "The system prompt that defines role, rules, format, and context. This is the persistent instruction set.",',
        '  "user": "The user message template. Use {{input}} for the dynamic user content placeholder."',
        '}',
        '',
        'Rules:',
        '- Output must be valid JSON with exactly two keys: "system" and "user"',
        '- The "system" value contains all role, rules, format, and context instructions',
        '- The "user" value is a template for the user-facing message',
        '- Use {{placeholder}} syntax for dynamic variables in the user message',
        '- The system message should be self-contained (do not reference the user message)',
        '- Escape newlines as \\n within the JSON string values',
        '- This format maps directly to the Anthropic Messages API structure',
      ].join('\n');

    default: {
      const _exhaustive: never = format;
      throw new Error(`Unhandled format: ${_exhaustive}`);
    }
  }
}
