'use client';

import { useEffect, useState } from 'react';
import { codeToHtml } from 'shiki';
import { useTheme } from 'next-themes';
import { ScrollArea, ScrollBar } from '@/components/ui/scroll-area';

interface CodeBlockProps {
  code: string;
  language: string;
}

export function CodeBlock({ code, language }: CodeBlockProps) {
  const [highlightedHtml, setHighlightedHtml] = useState<string>('');
  const [isLoading, setIsLoading] = useState(true);
  const { resolvedTheme } = useTheme();

  useEffect(() => {
    let cancelled = false;

    async function highlight() {
      try {
        // Map language names that Shiki might not recognize directly
        const langMap: Record<string, string> = {
          text: 'text',
          plaintext: 'text',
        };
        const lang = langMap[language] ?? language;

        const html = await codeToHtml(code, {
          lang,
          theme: resolvedTheme === 'dark' ? 'github-dark' : 'github-light',
        });

        if (!cancelled) {
          setHighlightedHtml(html);
          setIsLoading(false);
        }
      } catch {
        // If Shiki fails for any reason, fall back to plain rendering
        if (!cancelled) {
          setHighlightedHtml('');
          setIsLoading(false);
        }
      }
    }

    const run = () => {
      setIsLoading(true);
      highlight();
    };
    run();

    return () => {
      cancelled = true;
    };
  }, [code, language, resolvedTheme]);

  if (isLoading || !highlightedHtml) {
    return (
      <ScrollArea className="w-full rounded-md">
        <pre className="overflow-x-auto rounded-md bg-muted p-4 text-sm leading-relaxed">
          <code>{code}</code>
        </pre>
        <ScrollBar orientation="horizontal" />
      </ScrollArea>
    );
  }

  // Safety note: The HTML rendered here is generated by Shiki from trusted
  // application-generated code strings (from convertFormat). It is not
  // user-supplied HTML and does not require additional sanitization.
  return (
    <ScrollArea className="w-full rounded-md">
      <div
        className="shiki-container overflow-x-auto rounded-md text-sm leading-relaxed [&_pre]:p-4 [&_pre]:!bg-muted [&_code]:counter-reset-[line] [&_code_.line]:before:counter-increment-[line] [&_code_.line]:before:content-[counter(line)] [&_code_.line]:before:mr-4 [&_code_.line]:before:inline-block [&_code_.line]:before:w-4 [&_code_.line]:before:text-right [&_code_.line]:before:text-muted-foreground/50"
        dangerouslySetInnerHTML={{ __html: highlightedHtml }}
      />
      <ScrollBar orientation="horizontal" />
    </ScrollArea>
  );
}
